import { createFileRoute } from "@tanstack/react-router";
import { SiteHeader } from "@/components/SiteHeader";
import { buildMeta, canonicalLinks } from "@/lib/seo";
import { cityName, siteName } from "@/lib/city";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: buildMeta({
      title: `About | ${siteName()}`,
      description: `${siteName()} is an independent local news service for ${cityName()}, published daily.`,
      path: "/about",
    }),
    links: canonicalLinks("/about"),
  }),
  component: () => (
    <>
      <SiteHeader />
      <main className="container-read py-12">
        <h1 className="h1-news">About {siteName()}</h1>
        <p className="dek mt-3">
          Independent local news for {cityName()}, published daily.
        </p>
        <div className="prose-news mt-6">
          <p>
            {siteName()} covers local government, business, community life, property and the
            institutions that make {cityName()}. Our goal is to give {cityName()} residents a
            reliable, daily record of what is happening in their city, with every claim attributed
            and linked to its source.
          </p>

          <h2>How we produce our journalism</h2>
          <p>
            Our articles are generated by AI from named, publicly available sources that we link in
            every piece. Before anything publishes, each article passes an automated editorial
            screen. Anything that names a person or organisation in connection with crime, courts,
            allegations, misconduct or insolvency is held back and cannot publish until a person has
            reviewed it. Lower-risk articles, such as community roundups, guides and general local
            coverage, publish automatically once they pass the screen.
          </p>
          <p>
            Articles are bylined to the publication or desk, for example &ldquo;{siteName()}&rdquo;,
            not to an invented human author. We do not use fake personas or fabricated bios. For a
            full explanation of how we use AI, what is automated and what a human controls, see our{" "}
            <a href="/editorial-standards">editorial standards page</a>.
          </p>

          <h2>Publisher and ownership</h2>
          <p>
            {siteName()} is part of the Daily Network, a group of independent city news services
            across Australia. The network is owned and operated by SP Experts Pty Ltd, based in
            Canberra, ACT. The publisher sets editorial policy, owns the content guardrails and is
            accountable for everything we publish.
          </p>

          <h2>Corrections</h2>
          <p>
            We correct errors quickly and transparently. When we update a piece, we note the change
            on the article so the correction is on the record. If you spot something wrong, use our{" "}
            <a href="/contact">contact page</a>.
          </p>

          <h2>Contact</h2>
          <p>
            News tips, corrections and general enquiries: <a href="/contact">contact page</a>.
          </p>
        </div>
      </main>
    </>
  ),
});
