import { createFileRoute } from "@tanstack/react-router";
import { SiteHeader } from "@/components/SiteHeader";
import { buildMeta, canonicalLinks } from "@/lib/seo";
import { cityName, siteName } from "@/lib/city";

export const Route = createFileRoute("/editorial-standards")({
  head: () => ({
    meta: buildMeta({
      title: `AI and editorial standards | ${siteName()}`,
      description: `How ${siteName()} uses AI to report on ${cityName()}, where the human sits, and how we source, verify and correct our journalism.`,
      path: "/editorial-standards",
    }),
    links: canonicalLinks("/editorial-standards"),
  }),
  component: () => (
    <>
      <SiteHeader />
      <main className="container-read py-12">
        <h1 className="h1-news">AI and editorial standards</h1>
        <div className="prose-news mt-6">
          <p>
            {siteName()} is an AI-run local news and guides service for {cityName()}, part of a
            network of city sites built the same way. We think the honest thing to do is tell you
            exactly how that works, so this page sets out plainly how we use AI, what is automated,
            what a human controls, and how we source, verify and correct what we publish.
          </p>

          <h2>How we use AI</h2>
          <p>
            Our news articles and roundups are generated by AI. For each piece, the AI draws on
            named, publicly available sources that we link in the article, and we synthesise the
            facts from those sources rather than copying any of them. Before anything goes live,
            every piece passes an automated editorial screen. The screen looks for the higher-risk
            material, anything that names a person or organisation in connection with crime, court
            matters, allegations, misconduct or insolvency, and holds those pieces back. A held
            piece cannot publish until a person has reviewed it. Lower-risk pieces, such as community
            roundups, what-is-on guides and general local coverage, publish automatically once they
            pass the screen. Telling you this up front is the point. It is how you can judge what you
            are reading.
          </p>

          <h2>What is automated, and where the human sits</h2>
          <p>
            The articles, local-news syntheses, roundups and guides on this site are AI-generated. A
            human, the publisher, sets the editorial policy, decides the allow-list of sources the
            AI may draw on, sets the guardrails the system runs under, and reviews every piece the
            automated screen holds back before it can publish. Routine low-risk pieces publish
            automatically once they pass the screen; anything the screen flags as sensitive waits
            for a person. The publisher is accountable for everything we publish. In short: a person
            designs and stands behind the system, the system writes and screens the stories, and a
            person signs off on the sensitive ones.
          </p>

          <h2>Our guardrails</h2>
          <p>The system runs inside fixed limits:</p>
          <ul>
            <li>
              Every piece is screened before it can publish. Anything that names a person or
              organisation in connection with crime, courts, allegations, misconduct or insolvency
              is held back for human review and never goes live automatically.
            </li>
            <li>
              We only draw from an allow-list of public sources, and we always link them so you can
              see where a fact came from.
            </li>
            <li>
              We never reproduce or rewrite a single source article. We synthesise facts from
              several sources and attribute them.
            </li>
            <li>
              We exclude sensitive categories from AI synthesis, including crime and allegations
              against named individuals in court matters.
            </li>
            <li>
              Court and judgment items are link-out only. We point you to the official record and do
              not reproduce judgment text.
            </li>
            <li>
              We never scrape sites that prohibit it, including the major real-estate portals.
            </li>
          </ul>

          <h2>Sourcing and verification</h2>
          <p>
            Every AI article links the public sources it drew on, so you can check our work against
            the originals. For our how-to and figures content, our guides, we tell you plainly to
            confirm current figures with the official sources we link, because rates, fees, dates
            and rules change and the live source is always the authority.
          </p>

          <h2>Accuracy and corrections</h2>
          <p>
            We correct errors quickly and transparently. When we fix a piece, we append a visible
            "Updated" or "Corrected" note to the article so the change is on the record rather than
            quietly edited away. If you spot something wrong, please tell us via our{" "}
            <a href="/contact">contact page</a> and we will look at it.
          </p>

          <h2>Bylines</h2>
          <p>
            Automated pieces are bylined to the publication or desk, for example "{siteName()}",
            never to an invented human author. We do not use fake personas, AI-generated author
            photos or fabricated bios. If a name is not on a story, that is because no single person
            wrote it, and we would rather be straight with you than dress the work up as something
            it is not.
          </p>

          <h2>Accountability</h2>
          <p>
            {siteName()} and its publisher are accountable for what appears here at the masthead
            level. The publisher sets the policy, owns the guardrails and answers for the
            publication. Questions, corrections and concerns can all be raised through our{" "}
            <a href="/contact">contact page</a>.
          </p>
        </div>
      </main>
    </>
  ),
});
