import { createFileRoute } from "@tanstack/react-router";
import { SiteHeader } from "@/components/SiteHeader";
import { buildMeta, canonicalLinks } from "@/lib/seo";
import { siteName, siteEmail } from "@/lib/city";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: buildMeta({
      title: `Terms of Use | ${siteName()}`,
      description: `The terms that govern your use of ${siteName()}.`,
      path: "/terms",
    }),
    links: canonicalLinks("/terms"),
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <>
      <SiteHeader />
      <main className="container-read py-12">
        <h1 className="h1-news">Terms of Use</h1>
        <p className="meta mt-2">Last updated: 26 June 2026.</p>
        <div className="prose-news mt-6">
          <p>
            By accessing or using {siteName()} (the "site") or subscribing to our
            newsletter, you agree to these terms. If you do not agree, please do not
            use the site.
          </p>

          <h2>Acceptable use</h2>
          <p>
            You agree to use the site lawfully and respectfully. You must not attempt
            to disrupt the service, scrape content at scale, misuse forms or comments,
            impersonate anyone, or use the site to send unsolicited messages.
          </p>

          <h2>Intellectual property</h2>
          <p>
            All content on {siteName()} — including text, images, audio, design, and
            code — is copyright {siteName()} or its licensors unless otherwise marked.
            You may share short extracts with clear credit and a link back to the
            original article. You may not republish full articles, retransmit our
            newsletter, or use our content to train machine-learning models without
            our written permission.
          </p>
          <p>
            Articles on {siteName()} are generated by AI from publicly available sources and are not
            reviewed by a human editor before publication. Our{" "}
            <a href="/editorial-standards">editorial standards</a> page explains how we use AI.
          </p>

          <h2>Third-party content and links</h2>
          <p>
            The site links to third-party websites and quotes external sources. We
            are not responsible for the content, accuracy, or practices of any
            third-party site.
          </p>

          <h2>Disclaimer and limitation of liability</h2>
          <p>
            Content is provided for general information only and is not professional,
            legal, financial, or medical advice. We take care with reporting but do
            not warrant that the site or newsletter is error-free, complete, or
            uninterrupted. To the maximum extent permitted by law, {siteName()} is not
            liable for any indirect, incidental, special, or consequential loss
            arising from your use of the site. Nothing in these terms excludes any
            rights you have under the Australian Consumer Law that cannot lawfully
            be excluded.
          </p>

          <h2>Changes</h2>
          <p>
            We may update these terms from time to time. The "last updated" date
            above will change when we do. Continued use means you accept the updated
            terms.
          </p>

          <h2>Governing law</h2>
          <p>
            These terms are governed by the laws of the Australian Capital Territory,
            Australia. Any dispute will be heard in the courts of the ACT.
          </p>

          <h2>Contact</h2>
          <p>
            Questions about these terms:{" "}
            <a href={`mailto:${siteEmail("hello")}`}>
              {siteEmail("hello")}
            </a>
            .
          </p>
        </div>
      </main>
    </>
  );
}
