// "How we report this" — a transparency note shown under the article byline.
// Uses a native <details> element so it's collapsible, open by default
// (readers on any device can collapse it; we don't hide it on mobile by
// default to keep the E-E-A-T signal visible to crawlers without JS).
import { Info } from "lucide-react";
import { cityName, siteName } from "@/lib/city";

export function HowWeReportThis() {
  return (
    <details
      open
      className="how-we-report group mt-4 border-l-2 border-[var(--ink-red,#A32D2D)] bg-[var(--surface,#e8e4dd)] px-4 py-3 print:hidden"
    >
      <summary className="flex cursor-pointer list-none items-center gap-2 text-xs uppercase tracking-[0.14em] text-[var(--ink,#2d2d2d)]">
        <Info size={14} aria-hidden />
        <span>How we reported this</span>
        <span
          aria-hidden
          className="ml-auto text-[var(--ink-grey,#6b6b6b)] transition-transform group-open:rotate-180"
        >
          ▾
        </span>
      </summary>
      <p className="meta mt-2 leading-relaxed">
        This article was generated by AI from the linked public sources. {siteName()} is independently
        owned and covers {cityName()} news free from advertiser or sponsor influence.{" "}
        <a href="/editorial-standards" className="underline">
          Read our editorial standards →
        </a>
      </p>
    </details>
  );
}
